### ISSUE TITLE
Add api and domain categories | enhancement

### ISSUE THREAD

**Issue by st-clair-clarke** [srlee309/domain#4]
Congrats on a very good offering on something that is gaining some momentum.

Reading around the topic I see where two other distinct categories are proffered/used/recommended by some:

• api: Provides functionalities exposed to other domains
• domain: Domain logic like calculations, validations or facades for use cases and state management. .

Given the five categories currently offered by your package...:
• feature: Implements a use case with smart components
• data-access: Implements data accesses, e.g. via HTTP or WebSockets
• ui: Provides use case-agnostic and thus reusable components (dumb components)
• util: Provides helper functions
• shell: provide and entry point for multiple domain apps

...I am not seeing where to consistently put the api and domain categories.

In your five categories, where would you place the api and domain categories described above?

Please let me know what you think.

Cheers

**Comment by srlee309** [comment]
At the moment:
- domain would go in data-access.
- there wouldn't be anything specifically for api. If you want something from another domain just import it from the library. The api for the library is defined by the index.ts. 

I believe the above is the default NX way to do it. 

The two library types you mentioned I believe come from here: https://github.com/angular-architects/nx-ddd-plugin

It mentions:

> “Based on DDD, we have a few rules for communication between libraries to ensure consistent layering. For example, each library may only access libraries from the same domain or shared libraries.”

> “To prevent too much logic from being put into the shared area, the approach presented uses APIs that publish building blocks for other domains. This approach corresponds to Open Services in DDD.”

The difference between that and what this project currently has is that in this project:
 - Libraries can be consumed by any other domain as long as you setup the lint rules to allow consumption of the domain
 - Parent/child domains split up shared, so you can have shared at three levels: all applications, a single application and all child domains in a parent domain.

In general, I want to keep the types of libraries used as small as possible as it makes it harder to understand when you have more.

The benefit of adding api I think depends on the below questions:
 - The index.ts defines the library api. Is there value in defining an api at the domain level, so that you can have things private to a domain, i.e. only able to be used in that domain.
 - Is using a new library type the best approach for defining the inter-domain api. It could be done, for example, with another index.ts file. My assumption with the api library is that it just imports and then exports things, so it would have no impact on the affected performance.

For the domain library type, I don’t see the benefit and think its content should just go in the data-access library.

@st-clair-clarke  what do you think about the above and is there anything you can add. I will think about the above questions.

**Comment by srlee309** [comment]
I see the following as advantages to having a domain level api:
 - it is possible to consume things that should really only be for a single domain. If this happens, it would make changes more difficult. 
 - Instead of having to import from util and ui a domain level api would allow for these imports to be combined it into one import
 - along with the domain level api we can have a readme for the domain

I see these as the drawbacks.
 - if something consumes a library it is going to be affected by any changes to that library so any issues should be picked up by the tests.
 - Having to update two apis will be a hassle and an extra consideration

I am currently thinking of having another folder in the domain maybe something like .api which would have an index.ts and readme. The index.ts would by default just export everything in the domain libraries. It can then be restricted if desired. Before doing this, I would need to investigate if there would be any build size impact or affected performance impact.

**Comment by st-clair-clarke** [comment]
Thanks for the quick feedback. I understand what you have said and consider it a fair assessement. I hope there are plans to keep the package around for some time. I am going to use it in an application. Do you have an example of how the shell is used in an application?

**Comment by srlee309** [comment]
Shell combines the libraries so that you can import them with one import. The most common use case is when you want to lazyload the domain libraries for a route. 

```
const modules = [
    ApplicationDomainFeatureModule,
    ApplicationDomainDataAccessModule,
    ApplicationDomainUiModule,
    DomainRoutingModule
];

@NgModule({
    imports: [CommonModule, ...modules],
    exports: [...modules]
}) 
export class ApplicationDomainShellModule {}
```

FYI I created a gitter room https://gitter.im/srleecode/domain if you have any questions please feel free to use that room. Any feedback is appreciated.

**Comment by srlee309** [comment]
Looks like there is a build size impact if you use a simple domain api index like below:
```
export * from '../ui/src/index';
export * from '../util/src/index';
```

I had a domain shared/input with a ui and util library. The util library wasn't used in the application and it contained a large (2 megabyte) file.

Not importing any shared input library in the application gave a main.js of 39.42 kB
Importing only the shared/input ui library in the application gave a main.js of 39.79 kB
Importing only the ui library from the domain api index tsconfig path gave a main.js of  2.47 MB. This size means that the bundle included both the ui and util libraries even though the util library wasn't used.

I am closing this ticket as I don't know how to create a domain level api without causing a bundle size impact. I might create a new ticket if I can think of a way to do this. If anyone else knows more about tree shaking, would like this feature and knows how to create the domain api without causing a bundle size impact please raise a new ticket or create a PR.
